---
sudo: false
language: python

matrix:
  include:
    # Django 1.9, Wagtail 1.9
    - python: 2.7
      env: TOXENV=py27-django19-wagtail19
    - python: 3.5
      env: TOXENV=py35-django19-wagtail19
    - python: 3.6
      env: TOXENV=py36-django19-wagtail19

    # Django 1.10, Wagtail 1.10
    - python: 2.7
      env: TOXENV=py27-django110-wagtail110
    - python: 3.5
      env: TOXENV=py35-django110-wagtail110
    - python: 3.6
      env: TOXENV=py36-django110-wagtail110

    # Django 1.11, Wagtail 1.10
    - python: 2.7
      env: TOXENV=py27-django111-wagtail110
    - python: 3.5
      env: TOXENV=py35-django111-wagtail110
    - python: 3.6
      env: TOXENV=py36-django111-wagtail110

  allow_failures:
    - python: 3.5
      env: TOXENV=lint

install:
  - pip install tox codecov

script:
  - tox

after_success:
  - tox -e coverage-report
  - codecov

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: praekelt.org
  password:
    secure: IxPnc95OFNQsl7kFfLlLc38KfHh/W79VXnhEkdb2x1GZznOsG167QlhpAnyXIJysCQxgMMwLMuPOOdk1WIxOpGNM1/M80hNzPAfxMYWPuwposDdwoIc8SyREPJt16BXWAY+rAH8SHxld9p1YdRbOEPSSglODe4dCmQWsCbKjV3aKv+gZxBvf6pMxUglp2fBIlCwrE77MyMYh9iW0AGzD6atC2xN9NgAm4f+2WFlKCUL/MztLhNWdvWEiibQav6Tts7p8tWrsBVzywDW2IOy3O0ihPgRdISZ7QrxhiJTjlHYPAy4eRGOnYSQXvp6Dy8ONE5a6Uv5g3Xw2UmQo85sSMUs2VxR0G7d+PQgL0A7ENBQ5i7eSAFHYs8EswiGilW2A7mM4qRXwg9URLelYSdkM+aNXvR+25dCsXakiO4NjCz/BPgNzxPeQLlBdxR5vHugeM/XYuhy6CHlZrR/uueaO0X8RyhJcqeDjBy58IrwYS3Mpj7QCfBpQ9PqsqXEWV9BKwKiBXM2+3hkhawFDWa0GW2PDbORKtSLy/ORfGLx5Y9qxQYKEGvFQA3iqkTjrLj+KeUziKtuvEAcvsdBIJVIxeoHwdl+qqxEm8A7YuRBnWVxWc3jE6wBXboeFP92gVe/ueoXmY22riK9Ja0pli3TyNga8by9WM8Qp4D2ZqkVXHwg=
  on:
    tags: true
    all_branches: true
